import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npx wrangler types` — regenerate, don't hand-edit.
    "worker-configuration.d.ts",
    // Generated by `npm run cf:build` (OpenNext) — not source, not committed.
    ".open-next/**",
  ]),
]);

export default eslintConfig;
